#!/bin/bash
#PBS -N nCnR10g
#PBS -M donguk.kim@ufl.edu
#PBS -m bea
#PBS -j oe
#PBS -l select=4:ncpus=36:mpiprocs=16
#PBS -l walltime=96:00:0
##PBS -l place=excl
#PBS -P moose

APPPATH=$MYPRJ_DIR/MOOSE/projects/coupling_xolotl_new
RUNPATH=/home/kimdong/scratch/ICvary_nCnR/10gr
mpirun $APPPATH/coupling_xolotl_new-opt -i $RUNPATH/GPM_GT_ic_from_file.i
#mpirun $APPPATH/coupling_xolotl_new-opt -i $RUNPATH/Postprocs_pore_frac_CnR.i
