#!/bin/bash
#PBS -N CnR128
#PBS -M donguk.kim@ufl.edu
#PBS -m bea
#PBS -j oe
#PBS -l select=4:ncpus=32:mpiprocs=32:mem=32gb
#PBS -l walltime=08:00:0
#PBS -l place=excl
#PBS -P moose

#APPPATH=/home/kimdong/projects/coupling_xolotl
APPPATH=$MYPRJ_DIR/MOOSE/projects/coupling_xolotl_new
RUNPATH=/home/kimdong/scratch/scaling_strong/CnR
mpirun $APPPATH/coupling_xolotl_new-opt -i $RUNPATH/PFmulti_bubble_master_20um_kdec_clu_noRes.i
