#!/bin/bash
#PBS -N test2d
#PBS -M sblondel@utk.edu
#PBS -m bea
#PBS -j oe
#PBS -l select=1:ncpus=36:mpiprocs=36
#PBS -l walltime=0:30:0
#PBS -P nsuf

cd $PBS_O_WORKDIR
export LD_LIBRARY_PATH=/projects/NE_SciDAC/dependencies/boost_1_70_0-install/lib:/projects/NE_SciDAC/dependencies/xolotl-sophie/build/lib:/projects/NE_SciDAC/dependencies/hdf5-1.10.5-install/lib:$LD_LIBRARY_PATH
module load impi
mpirun ./coupling_xolotl-opt -i PFmulti_bubble_master_20um_kdec.i
